apiVersion: v1
kind: Namespace
metadata:
  name: restaurant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant
  namespace: restaurant
  labels:
    app: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      name: restaurant
      labels:
        app: restaurant
    spec:
      containers:
        - name: restaurant
          image: marcusantunius/restaurant:v1
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant
  namespace: restaurant
spec:
  selector:
    app: restaurant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
  type: ClusterIP
