apiVersion: v1
kind: Namespace
metadata:
  name: restaurant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant
  namespace: restaurant
  labels:
    app: restaurant
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      name: restaurant
      labels:
        app: restaurant
        version: v1
    spec:
      containers:
        - name: restaurant
          image: marcusantunius/restaurant:v1
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant
  namespace: restaurant
spec:
  selector:
    app: restaurant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restaurant
  namespace: restaurant
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: restaurant
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: restaurant
                port:
                  number: 80
