data class Friend(val id: Int, val name: String)

data class Person(
    val _id: String,
    val index: Int,
    val guid: String,
    val isActive: Boolean,
    val balance: String,
    val picture: String,
    val age: Int,
    val eyeColor: String,
    val name: String,
    val gender: String,
    val company: String,
    val email: String,
    val phone: String,
    val address: String,
    val about: String,
    val registered: String,
    val latitude: Double,
    val longitude: Double,
    val tags: List<String>,
    val friends: List<Friend>,
    val greeting: String,
    val favoriteFruit: String
)

object Response {

    fun get() = listOf(
        Person(
            _id = "6550cdb022575940eb862648",
            index = 0,
            guid = "25296b68-17cb-44a9-9844-eb54308bab18",
            isActive = false,
            balance = "$3,513.48",
            picture = "http://placehold.it/32x32",
            age = 39,
            eyeColor = "brown",
            name = "Opal Kelley",
            gender = "female",
            company = "ZIDANT",
            email = "opalkelley@zidant.com",
            phone = "+1 (859) 472-2299",
            address = "847 Emerson Place, Reno, Guam, 2290",
            about = "Minim sint labore dolore sit culpa. Et do elit esse et minim consequat exercitation id. Amet tempor magna ullamco mollit amet excepteur enim tempor duis nulla nostrud eu eu. Et dolore occaecat officia aute dolor ex cupidatat. Voluptate est ut veniam adipisicing proident sit nostrud duis non duis ea eu duis aliquip. Occaecat incididunt non labore eiusmod quis consequat fugiat consequat culpa.\r\n",
            registered = "2018-05-07T05:48:40 +03:00",
            latitude = 83.937793,
            longitude = -18.728859,
            tags = listOf("adipisicing", "velit", "ex", "commodo", "cupidatat", "in", "adipisicing"),
            friends = listOf(
                Friend(id = 0, name = "Bradley Winters"),
                Friend(id = 1, name = "Snyder Olsen"),
                Friend(id = 2, name = "Christie Castillo")
            ),
            greeting = "Hello, Opal Kelley! You have 9 unread messages.",
            favoriteFruit = "banana"
        ),
        Person(
            _id = "6550cdb02197f8f384ea04f4",
            index = 1,
            guid = "d3b4b7ea-e0ff-44e1-8234-1828189cf286",
            isActive = false,
            balance = "$3,282.06",
            picture = "http://placehold.it/32x32",
            age = 28,
            eyeColor = "blue",
            name = "Rosetta Hayden",
            gender = "female",
            company = "GENEKOM",
            email = "rosettahayden@genekom.com",
            phone = "+1 (860) 428-3103",
            address = "227 Joval Court, Utting, Arkansas, 7651",
            about = "Ullamco commodo laboris laborum non aute irure nostrud pariatur veniam. Laborum est ea occaecat Lorem et eiusmod cillum duis in. Eiusmod exercitation exercitation ut veniam mollit aliquip sunt sit eiusmod consequat est dolor. Minim proident laboris commodo fugiat proident consequat tempor consectetur commodo. Laborum sunt irure voluptate in sit veniam esse officia voluptate. Ad elit voluptate labore do occaecat proident ipsum elit culpa laborum proident.\r\n",
            registered = "2014-01-20T02:42:05 +02:00",
            latitude = -27.652619,
            longitude = -170.407934,
            tags = listOf("sunt", "voluptate", "veniam", "consequat", "Lorem", "occaecat", "labore"),
            friends = listOf(
                Friend(id = 0, name = "Karla Clements"),
                Friend(id = 1, name = "Barry Bender"),
                Friend(id = 2, name = "Kathy Mclean")
            ),
            greeting = "Hello, Rosetta Hayden! You have 3 unread messages.",
            favoriteFruit = "strawberry"
        ),
        Person(
            _id = "6550cdb050e7d23fa11718e2",
            index = 2,
            guid = "6187260c-82e9-41c0-b176-89cd0d3737da",
            isActive = true,
            balance = "$2,824.29",
            picture = "http://placehold.it/32x32",
            age = 23,
            eyeColor = "blue",
            name = "Combs Walls",
            gender = "male",
            company = "FLUMBO",
            email = "combswalls@flumbo.com",
            phone = "+1 (970) 506-3215",
            address = "182 Corbin Place, Chemung, Iowa, 985",
            about = "Ex est id cillum pariatur reprehenderit tempor voluptate magna ea quis aliqua proident commodo est. Dolor ex ipsum ullamco tempor. Lorem commodo ea laborum non nostrud proident amet pariatur aliquip sit amet ad. Ea aute do commodo culpa sunt eu occaecat culpa magna. Dolore cillum sunt voluptate sint nisi deserunt ea ipsum minim enim nulla est adipisicing. Lorem non quis minim consectetur. Veniam laborum laboris cillum elit exercitation aliquip pariatur aute aliqua aliquip occaecat velit.\r\n",
            registered = "2016-08-12T01:52:36 +03:00",
            latitude = -64.949766,
            longitude = 0.656298,
            tags = listOf("incididunt", "ea", "dolore", "proident", "proident", "reprehenderit", "excepteur"),
            friends = listOf(
                Friend(id = 0, name = "Webster Perkins"),
                Friend(id = 1, name = "Moran Miranda"),
                Friend(id = 2, name = "Jarvis Padilla")
            ),
            greeting = "Hello, Combs Walls! You have 7 unread messages.",
            favoriteFruit = "strawberry"
        ),
        Person(
            _id = "6550cdb0bdcea88dd27deb05",
            index = 3,
            guid = "314f85f1-943d-49e9-9a59-552343d820e0",
            isActive = true,
            balance = "$2,658.54",
            picture = "http://placehold.it/32x32",
            age = 30,
            eyeColor = "blue",
            name = "Castro Meadows",
            gender = "male",
            company = "PHOLIO",
            email = "castromeadows@pholio.com",
            phone = "+1 (826) 468-2302",
            address = "487 Evergreen Avenue, Carlton, Missouri, 7041",
            about = "Ut aliquip officia incididunt aliquip laborum esse. Veniam labore cillum ut quis nisi ex veniam officia reprehenderit laborum. Laborum dolor sunt laboris anim pariatur. Amet non excepteur sunt do voluptate qui irure fugiat duis duis tempor.\r\n",
            registered = "2023-08-04T02:26:48 +03:00",
            latitude = 18.465325,
            longitude = -43.549376,
            tags = listOf("eu", "dolore", "minim", "excepteur", "ex", "proident", "commodo"),
            friends = listOf(
                Friend(id = 0, name = "Molly Gentry"),
                Friend(id = 1, name = "Geneva Preston"),
                Friend(id = 2, name = "Burch Mccray")
            ),
            greeting = "Hello, Castro Meadows! You have 1 unread messages.",
            favoriteFruit = "apple"
        ),
        Person(
            _id = "6550cdb007eeb5af8b70ff42",
            index = 4,
            guid = "efba43d9-1715-4905-86d3-a963c1472e3a",
            isActive = true,
            balance = "$3,804.02",
            picture = "http://placehold.it/32x32",
            age = 38,
            eyeColor = "green",
            name = "Mabel Shaffer",
            gender = "female",
            company = "CUBIX",
            email = "mabelshaffer@cubix.com",
            phone = "+1 (892) 563-3279",
            address = "151 Fiske Place, Magnolia, New Hampshire, 6161",
            about = "Ullamco id excepteur veniam enim dolor laboris velit sint ipsum elit enim. Sint aute velit veniam dolore non ea. Elit nulla aute ea in nisi aliqua nulla id aute ex proident.\r\n",
            registered = "2022-08-01T04:04:37 +03:00",
            latitude = -4.599958,
            longitude = -131.412042,
            tags = listOf("nulla", "dolore", "sint", "excepteur", "eiusmod", "do", "sit"),
            friends = listOf(
                Friend(id = 0, name = "Gray Holman"),
                Friend(id = 1, name = "Kristy Rivas"),
                Friend(id = 2, name = "Porter Cameron")
            ),
            greeting = "Hello, Mabel Shaffer! You have 1 unread messages.",
            favoriteFruit = "strawberry"
        ),
        Person(
            _id = "6550cdb0ee84e142ac4d473a",
            index = 5,
            guid = "2f1a7157-dfba-4b3e-813b-c3120a3a0218",
            isActive = true,
            balance = "$2,705.39",
            picture = "http://placehold.it/32x32",
            age = 29,
            eyeColor = "blue",
            name = "Leila Duncan",
            gender = "female",
            company = "AQUASSEUR",
            email = "leiladuncan@aquasseur.com",
            phone = "+1 (875) 426-2103",
            address = "684 Evans Street, Warren, Minnesota, 6545",
            about = "Excepteur do est ad et duis ut irure nisi ad minim tempor do ullamco. Ex ullamco cupidatat exercitation pariatur nostrud. Ipsum anim fugiat incididunt minim consequat sunt adipisicing ad ullamco excepteur sunt. Pariatur et exercitation sunt elit ut. Amet labore id aute esse cupidatat labore consequat. Veniam ex officia magna incididunt officia anim enim non fugiat aute proident irure Lorem mollit. Exercitation officia aute labore aliqua.\r\n",
            registered = "2014-01-04T11:09:01 +02:00",
            latitude = -36.662166,
            longitude = 149.791831,
            tags = listOf("incididunt", "eu", "officia", "dolor", "ad", "culpa", "elit"),
            friends = listOf(
                Friend(id = 0, name = "Aimee Rios"),
                Friend(id = 1, name = "Mcfadden Ramirez"),
                Friend(id = 2, name = "Hebert Serrano")
            ),
            greeting = "Hello, Leila Duncan! You have 4 unread messages.",
            favoriteFruit = "apple"
        ),
        Person(
            _id = "6550cdb09652decae14a3f9d",
            index = 6,
            guid = "672b2d15-dd19-4a43-8b7b-21677c5f5658",
            isActive = true,
            balance = "$2,451.78",
            picture = "http://placehold.it/32x32",
            age = 31,
            eyeColor = "blue",
            name = "Selena Morris",
            gender = "female",
            company = "ZIORE",
            email = "selenamorris@ziore.com",
            phone = "+1 (887) 567-2604",
            address = "921 Raleigh Place, Keyport, Wyoming, 2210",
            about = "Aliqua amet mollit aliqua irure eiusmod. Et incididunt magna consectetur aute. Elit nostrud ut non ut est nisi ut. Duis aliqua qui minim exercitation culpa ipsum nisi. Reprehenderit reprehenderit id excepteur veniam elit velit velit eu sit deserunt proident do aliquip est. Qui anim ullamco ad consequat velit eu ipsum magna.\r\n",
            registered = "2020-09-17T08:34:08 +03:00",
            latitude = -72.570319,
            longitude = -171.198936,
            tags = listOf("commodo", "ea", "ea", "aliqua", "ipsum", "voluptate", "mollit"),
            friends = listOf(
                Friend(id = 0, name = "Kent Wilkinson"),
                Friend(id = 1, name = "Wilkins Sargent"),
                Friend(id = 2, name = "Coffey Burris")
            ),
            greeting = "Hello, Selena Morris! You have 7 unread messages.",
            favoriteFruit = "apple"
        )
    )


}
