package com.marcus.restaurant.controller

// To parse the JSON, install jackson-module-kotlin and do:
//
//   val welcome = Welcome.fromJson(jsonString)


import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.PropertyNamingStrategy
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import com.fasterxml.jackson.module.kotlin.readValue

val mapper = jacksonObjectMapper().apply {
    propertyNamingStrategy = PropertyNamingStrategy.LOWER_CAMEL_CASE
    setSerializationInclusion(JsonInclude.Include.NON_NULL)
}

data class Welcome (
    val station: String? = null,
    val likely: String? = null,
    val grew: Boolean? = null,
    val creature: Double? = null,
    val rock: String? = null,
    val tight: Boolean? = null,
    val wild: Wild? = null,
    val during: Double? = null,
    val unusual: Double? = null,
    val outline: Boolean? = null,
    val almost: Boolean? = null,
    val task: String? = null,
    val they: Double? = null,
    val fix: Boolean? = null,
    val party: String? = null,
    val outside: Long? = null,
    val mix: Double? = null,
    val owner: Boolean? = null,
    val please: String? = null,
    val elephant: Boolean? = null,
    val process: String? = null,
    val fastened: Boolean? = null,
    val magic: String? = null,
    val wise: String? = null,
    val seven: String? = null,
    val world: String? = null,
    val excited: Long? = null,
    val student: Double? = null,
    val bag: Boolean? = null,
    val swing: Long? = null,
    val card: String? = null,
    val quick: Boolean? = null,
    val circle: String? = null,
    val history: Boolean? = null,
    val eaten: String? = null,
    val stepped: Double? = null,
    val nation: Double? = null,
    val section: Boolean? = null,
    val pen: String? = null,
    val policeman: Boolean? = null,
    val brick: Long? = null,
    val needed: Boolean? = null,
    val managed: Double? = null,
    val beside: String? = null,
    val depth: String? = null,
    val year: Boolean? = null,
    val milk: Double? = null,
    val numeral: Long? = null,
    val held: Boolean? = null,
    val apart: String? = null,
    val enter: Long? = null,
    val capital: Double? = null,
    val bridge: Boolean? = null,
    val familiar: Long? = null,
    val jungle: Boolean? = null,
    val noun: Long? = null
) {
    fun toJson() = mapper.writeValueAsString(this)

    companion object {
        fun fromJson(json: String) = mapper.readValue<Welcome>(json)
    }
}

data class Wild (
    val grew: String? = null,
    val met: Boolean? = null,
    val different: String? = null,
    val middle: Middle? = null,
    val empty: String? = null,
    val own: String? = null,
    val replied: String? = null,
    val putting: String? = null,
    val point: Long? = null,
    val use: Boolean? = null,
    val fully: String? = null,
    val chair: Long? = null,
    val seems: Boolean? = null,
    val third: Boolean? = null,
    val material: Long? = null,
    val ride: Boolean? = null,
    val bean: String? = null,
    val total: String? = null,
    val hospital: String? = null,
    val horse: Double? = null,
    val per: String? = null,
    val choose: String? = null,
    val conversation: String? = null,
    val speed: Boolean? = null,
    val parts: Boolean? = null,
    val eight: String? = null,
    val facing: Long? = null,
    val modern: Boolean? = null,
    val till: Boolean? = null,
    val railroad: Double? = null,
    val bent: Boolean? = null,
    val faster: Double? = null,
    val run: Boolean? = null,
    val vote: Long? = null,
    val needle: Double? = null,
    val describe: String? = null,
    val vertical: Boolean? = null,
    val figure: Double? = null,
    val brass: String? = null,
    val could: Double? = null,
    val unknown: String? = null,
    val vast: Double? = null,
    val visit: Long? = null,
    val pine: Double? = null,
    val loud: String? = null,
    val engineer: Long? = null,
    val stood: String? = null,
    val board: Boolean? = null,
    val broke: String? = null,

    @get:JsonProperty("package")@field:JsonProperty("package")
    val wildPackage: String? = null,

    val pole: Boolean? = null,
    val art: String? = null,
    val catch: Double? = null,
    val north: Double? = null,
    val held: String? = null,
    val bear: Double? = null,
    val most: String? = null,
    val rays: Double? = null,
    val lonely: Boolean? = null
)

data class Middle (
    val horn: Long? = null,
    val lion: Boolean? = null,
    val mental: Boolean? = null,
    val cannot: Long? = null,
    val ten: Double? = null,
    val aid: String? = null,
    val whispered: Whispered? = null,
    val fought: String? = null,
    val stretch: Long? = null,
    val market: Long? = null,
    val seems: String? = null,
    val shells: Boolean? = null,
    val loss: Boolean? = null,
    val quarter: Boolean? = null,
    val life: Double? = null,
    val along: String? = null,
    val grass: String? = null,
    val universe: Double? = null,
    val individual: Double? = null,
    val immediately: Double? = null,
    val care: Double? = null,
    val equator: String? = null,
    val headed: Long? = null,
    val forgotten: String? = null,
    val adventure: Double? = null,
    val family: Double? = null,
    val molecular: Boolean? = null,
    val built: String? = null,
    val position: String? = null,
    val forest: Double? = null,
    val ocean: Boolean? = null,
    val beside: Boolean? = null,
    val future: Long? = null,
    val symbol: String? = null,
    val unusual: Double? = null,
    val complete: Long? = null,
    val bread: Boolean? = null,
    val tight: Boolean? = null,
    val eventually: Boolean? = null,
    val behavior: Boolean? = null,
    val organization: Boolean? = null,
    val operation: String? = null,
    val national: Boolean? = null,
    val golden: String? = null,
    val asleep: String? = null,
    val above: Boolean? = null,
    val worse: Boolean? = null,
    val noon: Boolean? = null,
    val slave: Boolean? = null,
    val poem: String? = null,
    val window: Double? = null,
    val bottom: String? = null,
    val tribe: Boolean? = null,
    val surface: Double? = null,
    val continued: Boolean? = null,
    val greatly: Double? = null,
    val lot: String? = null,
    val telephone: Boolean? = null,
    val neighbor: Long? = null,
    val ought: Boolean? = null
)

data class Whispered (
    val proud: Proud? = null,
    val fourth: Boolean? = null,
    val press: Long? = null,
    val thus: Long? = null,
    val mill: Boolean? = null,
    val serious: Long? = null,
    val face: Boolean? = null,
    val blank: Double? = null,
    val replied: Boolean? = null,
    val leaf: String? = null,
    val window: Boolean? = null,
    val said: Long? = null,
    val am: String? = null,
    val research: Long? = null,
    val dozen: Boolean? = null,
    val movie: Double? = null,
    val fish: Long? = null,
    val five: String? = null,
    val case: Boolean? = null,
    val stone: Double? = null,
    val victory: Long? = null,
    val experiment: String? = null,
    val known: Long? = null,
    val mainly: String? = null,
    val unhappy: Double? = null,
    val health: String? = null,
    val river: Boolean? = null,
    val pine: Boolean? = null,
    val bar: Double? = null,
    val please: String? = null,
    val variety: String? = null,
    val court: Long? = null,
    val lift: Double? = null,
    val blue: Boolean? = null,
    val danger: String? = null,
    val war: Boolean? = null,
    val thank: Double? = null,
    val two: Long? = null,
    val count: Boolean? = null,
    val quiet: Boolean? = null,
    val tea: Double? = null,
    val people: Boolean? = null,
    val slave: String? = null,
    val film: Double? = null,
    val after: String? = null,
    val form: String? = null,
    val canal: Boolean? = null,
    val favorite: Double? = null,
    val cup: Boolean? = null,
    val extra: Boolean? = null,
    val bound: Boolean? = null,
    val mouth: Boolean? = null,
    val corner: Double? = null,
    val during: Boolean? = null,
    val member: Boolean? = null,
    val just: Double? = null,
    val cost: Boolean? = null,
    val happily: Double? = null,
    val teach: String? = null
)

data class Proud (
    val evidence: Double? = null,
    val rise: Long? = null,

    @get:JsonProperty("do")@field:JsonProperty("do")
    val proudDo: Boolean? = null,

    val ice: String? = null,
    val closer: String? = null,
    val title: Boolean? = null,
    val length: String? = null,
    val spirit: Boolean? = null,
    val temperature: Long? = null,
    val fierce: Boolean? = null,
    val current: String? = null,
    val across: Across? = null,
    val box: Boolean? = null,
    val pencil: Double? = null,
    val ran: Boolean? = null,
    val complex: String? = null,
    val win: String? = null,
    val carbon: Boolean? = null,
    val spring: String? = null,
    val people: Boolean? = null,
    val dress: Boolean? = null,
    val sail: String? = null,
    val amount: String? = null,
    val prove: Boolean? = null,
    val regular: Boolean? = null,
    val saved: Boolean? = null,
    val shadow: Boolean? = null,
    val lot: Long? = null,
    val kids: Long? = null,
    val nor: String? = null,
    val tape: Boolean? = null,
    val evening: Boolean? = null,
    val hospital: String? = null,
    val smile: String? = null,
    val eaten: Double? = null,
    val honor: Boolean? = null,
    val mainly: String? = null,
    val ear: Long? = null,
    val examine: Boolean? = null,
    val government: Double? = null,
    val brown: Long? = null,
    val sum: String? = null,
    val book: String? = null,
    val planned: String? = null,
    val ring: String? = null,
    val pride: Boolean? = null,
    val hunt: String? = null,
    val kitchen: String? = null,
    val thrown: Long? = null,
    val too: String? = null,
    val later: Double? = null,
    val basic: String? = null,
    val tales: Long? = null,
    val political: Boolean? = null,
    val typical: String? = null,
    val poetry: Double? = null,
    val elephant: Double? = null
)

data class Across (
    val type: String? = null,
    val jack: Jack? = null,

    @get:JsonProperty("while")@field:JsonProperty("while")
    val acrossWhile: String? = null,

    val sets: Long? = null,
    val bend: Double? = null,
    val eight: Double? = null,
    val pan: Long? = null,
    val particular: String? = null,
    val enough: Long? = null,
    val built: String? = null,
    val social: Boolean? = null,
    val because: String? = null,
    val condition: String? = null,
    val numeral: String? = null,
    val owner: Boolean? = null,
    val collect: Long? = null,
    val sum: Boolean? = null,
    val indeed: String? = null,

    @get:JsonProperty("island")@field:JsonProperty("island")
    val island: Boolean? = null,

    val everything: Double? = null,
    val instead: Boolean? = null,
    val afraid: String? = null,
    val daughter: String? = null,
    val but: Double? = null,
    val later: Boolean? = null,
    val standard: Long? = null,
    val month: Boolean? = null,
    val football: Boolean? = null,
    val school: Double? = null,
    val tank: Boolean? = null,
    val meet: String? = null,
    val scale: Boolean? = null,
    val made: String? = null,
    val current: String? = null,
    val sense: Boolean? = null,
    val claws: Double? = null,
    val grow: Boolean? = null,
    val tightly: Double? = null,
    val joined: String? = null,
    val enjoy: Long? = null,
    val master: Boolean? = null,
    val contrast: Boolean? = null,
    val shore: Boolean? = null,
    val garage: Boolean? = null,
    val stop: String? = null,
    val article: Double? = null,
    val forest: Long? = null,
    val control: Boolean? = null,
    val feel: Boolean? = null,
    val column: Long? = null,
    val corner: Double? = null,
    val probably: String? = null,
    val pond: String? = null,
    val mix: String? = null,
    val blank: Long? = null,
    val hall: Boolean? = null,
    val rear: String? = null,
    val death: Boolean? = null,
    val simplest: String? = null
)

data class Jack (
    val move: Boolean? = null,
    val experience: Long? = null,
    val captured: String? = null,
    val gave: Gave? = null,
    val nothing: Boolean? = null,
    val again: Boolean? = null,
    val biggest: String? = null,
    val nest: String? = null,
    val older: String? = null,
    val youth: Boolean? = null,
    val win: Boolean? = null,
    val generally: String? = null,
    val poetry: Double? = null,
    val previous: Boolean? = null,
    val reach: Long? = null,
    val earn: Boolean? = null,
    val diameter: Double? = null,
    val dirt: Boolean? = null,
    val planned: String? = null,
    val including: String? = null,
    val basic: Double? = null,
    val duty: String? = null,
    val product: String? = null,

    @get:JsonProperty("in")@field:JsonProperty("in")
    val jackIn: String? = null,

    val wash: String? = null,
    val tower: Double? = null,
    val basis: Long? = null,
    val before: Boolean? = null,
    val fence: Double? = null,
    val accurate: Boolean? = null,
    val eaten: String? = null,
    val room: String? = null,
    val funny: Boolean? = null,
    val globe: String? = null,

    @get:JsonProperty("for")@field:JsonProperty("for")
    val jackFor: Boolean? = null,

    val maybe: Boolean? = null,
    val moon: String? = null,
    val unusual: String? = null,
    val jump: String? = null,
    val author: Long? = null,
    val military: String? = null,
    val special: String? = null,
    val jungle: String? = null,
    val forgotten: Boolean? = null,
    val vowel: Boolean? = null,
    val way: Boolean? = null,
    val yet: Long? = null,
    val mass: String? = null,
    val it: Long? = null,
    val base: String? = null,
    val sense: String? = null,
    val important: Long? = null,
    val noun: Long? = null,
    val dinner: String? = null,
    val up: Long? = null,
    val recognize: Double? = null,
    val graph: String? = null,
    val certainly: Boolean? = null,
    val present: Long? = null
)

data class Gave (
    val plenty: Long? = null,
    val railroad: String? = null,
    val likely: String? = null,
    val tune: Long? = null,
    val instrument: Boolean? = null,
    val complete: Boolean? = null,
    val worker: Double? = null,
    val simplest: Boolean? = null,
    val board: Board? = null,
    val push: String? = null,
    val bite: Boolean? = null,
    val only: Double? = null,
    val myself: Double? = null,
    val breakfast: Boolean? = null,
    val continued: String? = null,
    val fifty: Boolean? = null,
    val dawn: Long? = null,
    val surrounded: String? = null,
    val means: String? = null,
    val hurry: Long? = null,
    val open: Boolean? = null,
    val tide: Boolean? = null,
    val vote: String? = null,
    val cattle: String? = null,
    val ride: Double? = null,
    val harbor: Boolean? = null,
    val scientist: String? = null,
    val fact: String? = null,
    val drove: Boolean? = null,
    val afraid: String? = null,
    val should: Long? = null,
    val central: Boolean? = null,
    val paid: Boolean? = null,
    val second: Double? = null,
    val palace: String? = null,
    val example: Long? = null,
    val tears: Boolean? = null,
    val fine: Long? = null,
    val longer: Double? = null,
    val week: Double? = null,
    val get: Long? = null,
    val lying: Boolean? = null,
    val beat: String? = null,
    val given: Double? = null,
    val climate: Boolean? = null,
    val does: String? = null,
    val sharp: Long? = null,
    val desk: Long? = null,
    val comfortable: Boolean? = null,
    val pool: String? = null,
    val buffalo: Boolean? = null,
    val race: Long? = null,
    val asleep: Boolean? = null,
    val safe: String? = null,
    val begun: String? = null,
    val increase: Long? = null,
    val onto: String? = null,

    @get:JsonProperty("island")@field:JsonProperty("island")
    val island: Boolean? = null,

    val minute: String? = null,
    val play: Long? = null
)

data class Board (
    val cage: Boolean? = null,
    val partly: String? = null,
    val cost: Boolean? = null,
    val lips: Double? = null,
    val safe: Double? = null,
    val sat: String? = null,
    val bell: String? = null,
    val occasionally: Long? = null,
    val remain: Remain? = null,
    val grandfather: Long? = null,
    val collect: Double? = null,
    val personal: Double? = null,
    val per: String? = null,
    val immediately: Boolean? = null,
    val instance: Double? = null,
    val experience: Boolean? = null,
    val allow: Long? = null,
    val since: Double? = null,
    val other: String? = null,
    val nodded: Boolean? = null,
    val suggest: String? = null,
    val muscle: Double? = null,
    val identity: Boolean? = null,
    val broad: String? = null,
    val lion: Boolean? = null,
    val fruit: Boolean? = null,
    val chicken: String? = null,
    val elephant: Boolean? = null,
    val swimming: Double? = null,
    val active: String? = null,
    val fallen: Long? = null,
    val division: String? = null,
    val diameter: String? = null,
    val vast: String? = null,
    val fed: String? = null,
    val stove: Boolean? = null,
    val tobacco: String? = null,
    val frozen: Boolean? = null,
    val fat: Double? = null,
    val chamber: String? = null,
    val belong: Double? = null,
    val planet: String? = null,
    val felt: String? = null,
    val throat: String? = null,
    val open: String? = null,
    val cabin: String? = null,
    val printed: Double? = null,
    val desert: String? = null,
    val again: String? = null,
    val blow: Boolean? = null,
    val only: Double? = null,
    val clear: String? = null,
    val realize: Double? = null,
    val soon: Boolean? = null,
    val or: Long? = null,
    val life: String? = null,
    val farmer: String? = null,
    val smile: String? = null
)

data class Remain (
    val anybody: Double? = null,
    val generally: Double? = null,
    val inside: String? = null,
    val disappear: Long? = null,
    val proud: String? = null,
    val perhaps: String? = null,
    val contain: String? = null,
    val than: String? = null,
    val fear: String? = null,
    val closely: Boolean? = null,
    val front: Double? = null,
    val remove: Boolean? = null,
    val bicycle: Double? = null,
    val watch: Double? = null,
    val introduced: Double? = null,
    val system: Long? = null,
    val across: String? = null,
    val whale: String? = null,
    val both: String? = null,
    val evidence: Long? = null,
    val occur: String? = null,
    val involved: String? = null,
    val farm: Boolean? = null,
    val public: Boolean? = null,
    val broken: String? = null,
    val process: String? = null,
    val sight: Boolean? = null,
    val neck: Boolean? = null,
    val hair: String? = null,
    val stems: String? = null,
    val out: String? = null,
    val pen: Long? = null,
    val enemy: Boolean? = null,
    val sell: Boolean? = null,
    val fierce: String? = null,
    val hardly: Double? = null,
    val stage: String? = null,
    val sail: Double? = null,
    val south: Boolean? = null,
    val freedom: Boolean? = null,
    val sweet: Long? = null,
    val nervous: String? = null,
    val more: String? = null,
    val how: String? = null,
    val proper: String? = null,
    val product: Boolean? = null,
    val most: Double? = null,
    val low: String? = null,
    val remain: Double? = null,
    val rule: Double? = null,
    val arrow: Long? = null,
    val fix: Double? = null,
    val primitive: Boolean? = null,
    val hill: Boolean? = null,
    val wrote: Long? = null,
    val account: Boolean? = null,
    val represent: String? = null,
    val long: String? = null,
    val please: Boolean? = null,
    val before: Double? = null
)
